### ISSUE TITLE
FormatException: Could not find End of Central Directory Record

### ISSUE THREAD

**Issue by prasant10050** [Abdusin/dart-speed-test#1]
╭─ ~                                                 
╰─ pub global activate --source git https://github.com/Abdusin/dart-speed-test.git
The top level `pub` command is deprecated. Use `dart pub` instead.
Resolving dependencies... (2.7s)
+ archive 3.3.0
+ async 2.8.2
+ charcode 1.3.1
+ collection 1.16.0
+ console 4.1.0
+ crypto 3.0.1
+ file 6.1.2
+ http 0.13.4
+ http_parser 4.0.0
+ meta 1.7.0
+ path 1.8.1
+ platform 3.1.0
+ process 4.2.4
+ shell 2.0.0
+ source_span 1.8.2
+ speed_test 2.0.0 from git https://github.com/Abdusin/dart-speed-test.git at 5b8178
+ string_scanner 1.1.0
+ term_glyph 1.2.0
+ typed_data 1.3.0
+ vector_math 2.1.2
Downloading shell 2.0.0...
Downloading console 4.1.0...
Downloading archive 3.3.0...
Downloading collection 1.16.0...
Downloading vector_math 2.1.2...
Building package executables... (1.2s)
Built speed_test:speed_test.
Installed executable speedtest.
Activated speed_test 2.0.0 from Git repository "https://github.com/Abdusin/dart-speed-test.git".

╭─ ~                                       
╰─ speedtest                                                                 ─╯

	  Server : |
	     ISP : |
	 Latency : |
	Download : |
	  Upload : |
	  Upload : \Unhandled exception:
FormatException: Could not find End of Central Directory Record
#0      ZipDirectory._findSignature (package:archive/src/zip/zip_directory.dart:149:5)
#1      new ZipDirectory.read (package:archive/src/zip/zip_directory.dart:28:20)
#2      ZipDecoder.decodeBuffer (package:archive/src/zip_decoder.dart:19:30)
#3      ZipDecoder.decodeBytes (package:archive/src/zip_decoder.dart:14:12)
#4      decompileZip (package:speed_test/speed_test.dart:11:30)
<asynchronous suspension>
#5      run (package:speed_test/speed_test.dart:66:20)
<asynchronous suspension>
#6      main (file:///Users/prasantkumarpandey/.pub-cache/git/dart-speed-test-5b8178e20e36c78d79b2d06535afa0770632e9b1/bin/speed_test.dart:18:18)
<asynchronous suspension>
                                                                                                                                                                   ─╯

**Comment by whoizit** [comment]
```
❮ ~/.pub-cache/bin/speedtest 

	 Server : |
	    ISP : |
	Latency : |
	Download : |
	 Upload : |
Unhandled exception:
Unsupported operating system
#0      getOperatingSystemPreferences (package:speed_test/speed_test.dart:50:7)
#1      getSpeedTestDownloadUrl (package:speed_test/speed_test.dart:27:28)
#2      run (package:speed_test/speed_test.dart:65:36)
#3      main (file:///home/user/.pub-cache/git/dart-speed-test-5b8178e20e36c78d79b2d06535afa0770632e9b1/bin/speed_test.dart:18:35)
#4      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:33)
#5      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:192:26)
```
